# Generated by Django 2.1.7 on 2019-03-14 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='profiles.Profile')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('about', models.CharField(default='Description', max_length=400)),
                ('history', models.TextField(default='Update school history')),
                ('fee_structure', models.FileField(default='Update school fee structure', upload_to='')),
                ('events', models.FileField(default='Update school events', upload_to='')),
                ('updates', models.FileField(upload_to='', verbose_name='Add updates')),
                ('uniforms', models.URLField(default='')),
                ('location', geoposition.fields.GeopositionField(default='', max_length=42)),
                ('results', models.FileField(default='', upload_to='')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at', '-id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='schools.School'),
        ),
    ]
