# Generated by Django 2.1.7 on 2019-05-23 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='time',
            field=models.TimeField(default=datetime.time(10, 48, 11, 999910)),
        ),
    ]
