# Generated by Django 2.1.7 on 2019-05-23 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20190523_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='fee_structure',
        ),
        migrations.RemoveField(
            model_name='school',
            name='results',
        ),
        migrations.AlterField(
            model_name='update',
            name='time',
            field=models.TimeField(default=datetime.time(10, 48, 54, 299284)),
        ),
    ]
