# Generated by Django 2.1.7 on 2019-05-23 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20190523_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='time',
            field=models.TimeField(default=datetime.time(13, 4, 59, 834611)),
        ),
    ]
