# Generated by Django 2.1.7 on 2019-05-23 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20190523_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='time',
            field=models.TimeField(default=datetime.time(13, 9, 24, 562527)),
        ),
    ]
