# Generated by Django 2.1.7 on 2019-05-24 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20190523_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2019, 5, 24)),
        ),
        migrations.AlterField(
            model_name='school',
            name='about',
            field=models.CharField(blank=True, default="Update school's description", max_length=400),
        ),
        migrations.AlterField(
            model_name='school',
            name='history',
            field=models.TextField(blank=True, default='Update school history'),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(default=datetime.date(2019, 5, 24)),
        ),
        migrations.AlterField(
            model_name='update',
            name='time',
            field=models.TimeField(default=datetime.time(8, 50, 20, 892791)),
        ),
    ]
