# Generated by Django 2.1.7 on 2019-05-29 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20190524_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2019, 5, 29)),
        ),
        migrations.AlterField(
            model_name='school',
            name='about',
            field=models.TextField(default="Update school's description"),
        ),
        migrations.AlterField(
            model_name='school',
            name='history',
            field=models.TextField(default='Update school history'),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(default=datetime.date(2019, 5, 29)),
        ),
        migrations.AlterField(
            model_name='update',
            name='time',
            field=models.TimeField(default=datetime.time(16, 44, 1, 232674)),
        ),
    ]
