# Generated by Django 2.1.7 on 2019-06-19 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_auto_20190529_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_id']},
        ),
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ['update_id']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.RemoveField(
            model_name='update',
            name='id',
        ),
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='update',
            name='update_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2019, 6, 19)),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(default=datetime.date(2019, 6, 19)),
        ),
        migrations.AlterField(
            model_name='update',
            name='time',
            field=models.TimeField(default=datetime.time(10, 31, 2, 582036)),
        ),
    ]
