# Generated by Django 2.1.7 on 2019-06-19 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_auto_20190619_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='time',
            field=models.TimeField(default=datetime.time(10, 40, 51, 415820)),
        ),
    ]
