# Generated by Django 2.1.7 on 2019-06-19 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_auto_20190619_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='update',
            name='time',
            field=models.TimeField(default=datetime.time(10, 45, 54, 856067)),
        ),
        migrations.AlterField(
            model_name='update',
            name='update_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
