# Generated by Django 2.1.7 on 2019-06-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.TextField(default='Update level (e.g primary, secondary).'),
        ),
    ]
